### Running Tensors and Pytorch Objects in GPUs

In [10]:
! nvidia-smi

Thu Jan 26 23:23:35 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 528.24       Driver Version: 528.24       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   46C    P8    N/A /  30W |    506MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

#### Check for GPU access with pytorch

In [11]:
import torch 

In [12]:
torch.cuda.is_available()

True

#### Setup device agnostic code

In [13]:
device  = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

#### Count number of GPUs

In [14]:
torch.cuda.device_count()

1

#### Putting Tensors and Models in GPU

In [15]:
# create a Tensor
tensor = torch.Tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1., 2., 3.]) cpu


In [17]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1., 2., 3.], device='cuda:0')

In [18]:
#### Moving Tensors Back to CPU

In [20]:
tensors_on_cpu = tensor_on_gpu.cpu()
tensors_on_cpu, tensors_on_cpu.device

(tensor([1., 2., 3.]), device(type='cpu'))