In [1]:
import torch

### Reshaping , Stacking, Squeezing and unsquezzing tensors

* Reshaping - reshapes an input tensor of certain shape but keeps the same memory as the original tensor
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combining multiple tensors on top of each other  vstack or hstack 
* Squeeze - removes all `1` dimensions from tensor
* Unsqueez - add a ` 1` dimension to a target tensor 
* Permute - Retuen a view od the input with dimensions swapped in a certain way

In [8]:
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [7]:
# Reshaping
x_rehaped = x.reshape(3,3)
x_rehaped, x_rehaped.shape, x_rehaped.ndim

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]),
 2)

In [9]:
# Lets try Changing the View
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

#### Changing Z changes x because a view of a tensor shares the memory with the original

In [10]:
z[:,2] = 2
z,x

(tensor([[1, 2, 2, 4, 5, 6, 7, 8, 9]]), tensor([1, 2, 2, 4, 5, 6, 7, 8, 9]))

#### Stack Tensors OnTop of eachother

In [20]:
X_stacked = torch.stack([x,x,x,x],0)
X_stacked

tensor([[1, 2, 2, 4, 5, 6, 7, 8, 9],
        [1, 2, 2, 4, 5, 6, 7, 8, 9],
        [1, 2, 2, 4, 5, 6, 7, 8, 9],
        [1, 2, 2, 4, 5, 6, 7, 8, 9]])

#### Squeeze and Unsqueeze

In [23]:
x_rehaped, x_rehaped.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [29]:
x_reshaped = x_rehaped.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [32]:
x_reshaped.squeeze(),x_reshaped.squeeze().shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [34]:
x_squeeze = x_reshaped.squeeze()
x_unsqueeze = x_squeeze.unsqueeze(dim=0)
x_squeeze.shape, x_unsqueeze.shape

(torch.Size([9]), torch.Size([1, 9]))

#### Permute - rearranges the dimensions of target tensor in specified order

In [36]:
x_original = torch.rand(size=(224,224,3))
print(x_original.shape,x_original.ndim)
x_permute = torch.permute(x_original,dims=(2,1,0))
print(x_permute.shape, x_permute.ndim)

torch.Size([224, 224, 3]) 3
torch.Size([3, 224, 224]) 3


#### Indeing and Slicing

In [37]:
x = torch.arange(1,10).reshape(3,3)
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [54]:
x[:2,:2], x[0,:2],x[0][0], x[:,1], x[:,:]

(tensor([[1, 2],
         [4, 5]]),
 tensor([1, 2]),
 tensor(1),
 tensor([2, 5, 8]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))