### Manipulating Tensors (Tensor Oprations)

Tensor Operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [1]:
import torch
import numpy as np

In [22]:
# Bsic Operations 
tensor = torch.Tensor([1,2,3])
tensor + 10 , tensor * 10 , tensor / 2 , tensor

(tensor([11., 12., 13.]),
 tensor([10., 20., 30.]),
 tensor([0.5000, 1.0000, 1.5000]),
 tensor([1., 2., 3.]))

In [25]:
# BUilIn functions
torch.mul(tensor, 10)

tensor([10., 20., 30.])

In [23]:
tensor1 = torch.Tensor([[2,2], [2,2]])
tensor2 = torch.Tensor([[3,3],[3, 3]])
tensor3 = tensor1 * tensor2
tensor3

tensor([[6., 6.],
        [6., 6.]])

In [28]:
# for diff DImension matrixes
tensor1 = torch.Tensor([[2, 2], [2, 2], [2,2]])  # 3x2
tensor2 = torch.Tensor([[2,2],[2,2]])   # 2x2
torch.matmul(tensor1, tensor2)


tensor([[8., 8.],
        [8., 8.],
        [8., 8.]])

In [35]:
torch.matmul(torch.rand(4,4), torch.rand(4,9))

tensor([[0.4007, 1.1408, 0.6575, 0.4984, 1.2875, 0.7099, 0.7167, 0.4747, 1.2347],
        [0.6510, 1.2981, 0.4781, 0.5235, 1.1963, 0.9310, 0.6245, 0.3745, 1.1134],
        [0.6887, 1.8264, 0.6803, 0.8287, 1.7085, 1.1026, 1.0579, 1.0600, 1.5551],
        [0.7429, 0.7621, 1.0548, 0.4234, 1.2635, 0.3898, 1.0560, 1.4758, 1.1597]])

In [38]:
# Transposing 4x3 to 3x4 
torch.matmul(torch.rand(3,3), torch.rand(4,3).T)

tensor([[0.9218, 0.4981, 0.4076, 0.3301],
        [1.5248, 1.0664, 0.5556, 0.8626],
        [1.4178, 1.5928, 0.5692, 0.8794]])