In [23]:
import torch as th
import numpy as np

RANDOM_SEED = 40

### Pytorch Tensors & Numpy 
* Pytorch in many was internally utilizes numpy and because of this pytorch tensors and numpy can interact smoothly

In [16]:
# Note : when converting from numpy array to Pytorch Tensor , pytorh converts to dtype of float64
arrary = np.arange(1.0, 8.0)
tensor = th.from_numpy(arrary).type(th.float32)
arrary, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [17]:
# Change in array doesnt change the tensor itfelt , they have different memory spaces
arrary = arrary+10
arrary, tensor

(array([11., 12., 13., 14., 15., 16., 17.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]))

In [14]:
# Tensor to Numpy
tensor = th.ones(7)
array = tensor.numpy()
tensor, arrary

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([31., 22., 23., 24., 25., 26., 27.]))

In [27]:
th.manual_seed(RANDOM_SEED)
print(th.rand(3,3)) 
th.manual_seed(RANDOM_SEED)
print(th.rand(3,3))

tensor([[0.3679, 0.8661, 0.1737],
        [0.7157, 0.8649, 0.4878],
        [0.5501, 0.1318, 0.2897]])
tensor([[0.3679, 0.8661, 0.1737],
        [0.7157, 0.8649, 0.4878],
        [0.5501, 0.1318, 0.2897]])
