In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

#### Tensor DataTypes

In [13]:
float_32_tensor = torch.tensor([3.0 ,6.0 ,9.0],
                                                dtype=None,
                                                device=None,
                                                requires_grad=False)
float_32_tensor, float_32_tensor.dtype, float_32_tensor.device,float_32_tensor.requires_grad  # to see whats the default parameters even when they are set to None

(tensor([3., 6., 9.]), torch.float32, device(type='cpu'), False)

#### Type Conversion

In [15]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

#### Tensor Attributes

In [17]:
float_16_tensor + float_32_tensor, float_32_tensor* float_32_tensor

(tensor([ 6., 12., 18.]), tensor([ 9., 36., 81.]))

In [21]:
print(f"{float_32_tensor} \n Attributes \n Dtype => {float_32_tensor.dtype} \n Dimensions => {float_32_tensor.ndim} \n Shape => {float_32_tensor.shape} \n Device => {float_32_tensor.device}")

tensor([3., 6., 9.]) 
 Attributes 
 Dtype => torch.float32 
 Dimensions => 1 
 Shape => torch.Size([3]) 
 Device => cpu
