### Pytorch Fundamentals

In [1]:
print("Following Zero to Mastery Pytorch for Deep Learning & Machine Learning COurse")

Following Zero to Mastery Pytorch for Deep Learning & Machine Learning COurse


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
torch.__version__

'1.13.1+cu117'

#### Intro to Pytorch Tensors

In [4]:
# Creating Tensors

# 1.Scalar
scalar = torch.Tensor(7)
scalar

tensor([0., 0., 0., 0., 0., 0., 0.])

In [5]:
scalar.ndim

1

In [6]:
# 2.Vector 
vector = torch.Tensor([7,7])
vector,vector.ndim,vector.shape

(tensor([7., 7.]), 1, torch.Size([2]))

In [7]:
# 3.Matrix
matrix = torch.Tensor([[7,8],[9,10]])
matrix,matrix.ndim,matrix.shape

(tensor([[ 7.,  8.],
         [ 9., 10.]]),
 2,
 torch.Size([2, 2]))

In [8]:
matrix[0][0], matrix[0][0].item()

(tensor(7.), 7.0)

In [9]:
# 4. Tensor
tensor = torch.Tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]]])

tensor, tensor.ndim,tensor.shape

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 3,
 torch.Size([1, 3, 3]))

In [10]:
tensor[0][0][-1].item()

3.0

#### Creating Tensors Randomly

In [11]:
randTensor_1 = torch.rand(2,2,2)
randTensor_1, randTensor_1.ndim, randTensor_1.shape

(tensor([[[0.9659, 0.7023],
          [0.3343, 0.4686]],
 
         [[0.3842, 0.8559],
          [0.2329, 0.3630]]]),
 3,
 torch.Size([2, 2, 2]))

In [12]:
# Create a Random Tensor with simirlar shape as an image
random_image_size_tensor = torch.rand(size=(224,224,3))  # Height, width, color channel
random_image_size_tensor, random_image_size_tensor.ndim

(tensor([[[0.6856, 0.7738, 0.7939],
          [0.4551, 0.6486, 0.6013],
          [0.0053, 0.4603, 0.7936],
          ...,
          [0.6703, 0.8588, 0.5969],
          [0.9959, 0.7674, 0.7482],
          [0.4528, 0.0579, 0.6523]],
 
         [[0.3433, 0.7058, 0.9825],
          [0.9071, 0.2553, 0.4825],
          [0.5100, 0.5633, 0.1147],
          ...,
          [0.3939, 0.7916, 0.7149],
          [0.5831, 0.2210, 0.8284],
          [0.8355, 0.5821, 0.9001]],
 
         [[0.8680, 0.5363, 0.3316],
          [0.0027, 0.5165, 0.9394],
          [0.5837, 0.9633, 0.7444],
          ...,
          [0.1747, 0.7111, 0.4325],
          [0.4461, 0.5929, 0.7495],
          [0.9587, 0.5924, 0.7783]],
 
         ...,
 
         [[0.2321, 0.1416, 0.4760],
          [0.3899, 0.8320, 0.8426],
          [0.3715, 0.3446, 0.3413],
          ...,
          [0.0847, 0.3382, 0.1989],
          [0.8616, 0.9673, 0.4211],
          [0.3483, 0.3146, 0.7355]],
 
         [[0.3816, 0.0970, 0.2011],
          [0

#### Zeros and Ones Tensor

In [13]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [15]:
ones.dtype

torch.float32

#### Creating a Range of Tensors and Tensors-like

In [24]:
# Pretty same as Python's inbuilt Range Function
one_to_ten = torch.arange(0,10,2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [25]:
# Creating Tensors Like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])