### Pytorch Fundamentals

In [3]:
print("Following Zero to Mastery Pytorch for Deep Learning & Machine Learning COurse")

Following Zero to Mastery Pytorch for Deep Learning & Machine Learning COurse


In [9]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
torch.__version__

'1.13.1+cu117'

#### Intro to Pytorch Tensors

In [10]:
# Creating Tensors

# 1.Scalar
scalar = torch.Tensor(7)
scalar

tensor([0., 0., 0., 0., 0., 0., 0.])

In [11]:
scalar.ndim

1

In [17]:
# 2.Vector 
vector = torch.Tensor([7,7])
vector,vector.ndim,vector.shape

(tensor([7., 7.]), 1, torch.Size([2]))

In [21]:
# 3.Matrix
matrix = torch.Tensor([[7,8],[9,10]])
matrix,matrix.ndim,matrix.shape

(tensor([[ 7.,  8.],
         [ 9., 10.]]),
 2,
 torch.Size([2, 2]))

In [36]:
matrix[0][0], matrix[0][0].item()

(tensor(7.), 7.0)

In [29]:
# 4. Tensor
tensor = torch.Tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]]])

tensor, tensor.ndim,tensor.shape

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 3,
 torch.Size([1, 3, 3]))

In [33]:
tensor[0][0][-1].item()

3.0

#### Creating Tensors Randomly

In [52]:
randTensor_1 = torch.rand(2,2,2)
randTensor_1, randTensor_1.ndim, randTensor_1.shape

(tensor([[[0.1503, 0.8004],
          [0.9412, 0.0265]],
 
         [[0.1975, 0.3231],
          [0.6090, 0.9328]]]),
 3,
 torch.Size([2, 2, 2]))

In [54]:
# Create a Random Tensor with simirlar shape as an image
random_image_size_tensor = torch.rand(size=(224,224,3))  # Height, width, color channel
random_image_size_tensor, random_image_size_tensor.ndim

(tensor([[[0.6451, 0.2416, 0.7717],
          [0.1028, 0.1578, 0.9808],
          [0.7239, 0.9977, 0.7499],
          ...,
          [0.4168, 0.4781, 0.8864],
          [0.4882, 0.6571, 0.7146],
          [0.4828, 0.3529, 0.7824]],
 
         [[0.9893, 0.5282, 0.1599],
          [0.3164, 0.6266, 0.3941],
          [0.0571, 0.3135, 0.3398],
          ...,
          [0.5177, 0.6071, 0.3924],
          [0.6417, 0.9074, 0.0647],
          [0.4793, 0.3377, 0.9924]],
 
         [[0.1761, 0.6666, 0.4977],
          [0.6196, 0.5922, 0.2774],
          [0.4856, 0.5860, 0.4050],
          ...,
          [0.2968, 0.5180, 0.1994],
          [0.8550, 0.1426, 0.6274],
          [0.4404, 0.1246, 0.6056]],
 
         ...,
 
         [[0.7262, 0.6978, 0.6472],
          [0.7884, 0.1208, 0.9778],
          [0.3847, 0.1095, 0.2124],
          ...,
          [0.7796, 0.7640, 0.7584],
          [0.0957, 0.6808, 0.4029],
          [0.1703, 0.5082, 0.6363]],
 
         [[0.5720, 0.6497, 0.6354],
          [0

#### Zeros and Ones Tensor

In [66]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [67]:
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [68]:
ones.dtype

torch.float32