In [33]:
import torch
import numpy as np

### Initializing a Tensor

In [34]:
# Directly from Data
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [35]:
# From Numpy Array
np_array = np.array(data)
x_np = torch.tensor(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [36]:
# From another Tensor
x_ones = torch.ones_like(x_data)
print("Ones Tennsor => ", x_ones)

x_rand = torch.rand_like(x_data,dtype=torch.float)
print("Random Tennsor => ", x_rand)

Ones Tennsor =>  tensor([[1, 1],
        [1, 1]])
Random Tennsor =>  tensor([[0.4913, 0.1891],
        [0.7751, 0.0678]])


In [37]:
# With Random or Constant Values
shape = (3,2)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"{rand_tensor}\n{ones_tensor}\n{zeros_tensor}")

tensor([[0.1093, 0.3786],
        [0.7891, 0.3964],
        [0.3251, 0.4144]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


### Attributes of A Tensor

In [38]:
tensor = torch.rand(3,4,2)
print(tensor)
print(tensor.shape)
print(tensor.dtype)
print(tensor.ndim)
print(tensor.device)



tensor([[[0.4454, 0.1715],
         [0.3012, 0.8907],
         [0.9577, 0.2173],
         [0.6991, 0.7614]],

        [[0.4039, 0.3396],
         [0.9822, 0.4506],
         [0.3498, 0.8027],
         [0.6171, 0.8552]],

        [[0.3314, 0.7491],
         [0.7307, 0.2561],
         [0.8116, 0.2542],
         [0.2501, 0.9517]]])
torch.Size([3, 4, 2])
torch.float32
3
cpu


### Opearions on Tensors

In [39]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [40]:
tensor = torch.ones(4,4)
print("First Row => ", tensor[0,:])
print("First Column => ", tensor[:,0])
print("Last Column => ", tensor[:,-1])
print(tensor)

First Row =>  tensor([1., 1., 1., 1.])
First Column =>  tensor([1., 1., 1., 1.])
Last Column =>  tensor([1., 1., 1., 1.])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [41]:
t1 = torch.cat([tensor,torch.ones(4,4),torch.zeros(4,4)],dim=0)
t1

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Arithmetic Operations

In [42]:
tensor * torch.zeros(4,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [43]:
t1 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
t2 = t1.T
t1, t1.T

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[1, 4, 7],
         [2, 5, 8],
         [3, 6, 9]]))

In [44]:
t1 + t2 , t1 * t2 , t1 * 0 , t1 -t1, t1  / t2

(tensor([[ 2,  6, 10],
         [ 6, 10, 14],
         [10, 14, 18]]),
 tensor([[ 1,  8, 21],
         [ 8, 25, 48],
         [21, 48, 81]]),
 tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[1.0000, 0.5000, 0.4286],
         [2.0000, 1.0000, 0.7500],
         [2.3333, 1.3333, 1.0000]]))

In [45]:
t1[0][0].item()

1

In-place operations Operations that store the result into the operand are called in-place. They are denoted by a _ suffix.

In [46]:
t1.add_(100)
print(t1)

tensor([[101, 102, 103],
        [104, 105, 106],
        [107, 108, 109]])
